spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/samvaad
    username: samvaad
    password: samvaad

  jpa:
    hibernate:
      ddl-auto: validate

samvaad:
  auth:
    jwt-secret: ${SAMVAAD_JWT_SECRET}
  logging:
    file:
      name: logs/samvaad.log
      max-size: 10MB
      max-history: 50
